/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    variants: Variant;
    categories: Category;
    articles: Article;
    'variant-overrides': VariantOverride;
    sources: Source;
    media: Media;
    updates: Update;
    'contact-submissions': ContactSubmission;
    'answer-feedback': AnswerFeedback;
    'support-threads': SupportThread;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'variant-overrides': VariantOverridesSelect<false> | VariantOverridesSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    updates: UpdatesSelect<false> | UpdatesSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'answer-feedback': AnswerFeedbackSelect<false> | AnswerFeedbackSelect<true>;
    'support-threads': SupportThreadsSelect<false> | SupportThreadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'gmail-connection': GmailConnection;
  };
  globalsSelect: {
    'gmail-connection': GmailConnectionSelect<false> | GmailConnectionSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Redacteuren en beheerders van de beheeromgeving.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Beheerder kan alles inclusief varianten, rollen en AI-goedkeuring. Redacteur is beperkter.
   */
  role: 'admin' | 'editor';
  /**
   * Leeg = centrale redacteur (mag centrale artikelen schrijven). Ingevuld = variant-redacteur (mag uitsluitend afwijkingen voor déze variant schrijven, nooit de centrale boom). Zie docs/CONTENT-MODEL.md.
   */
  variantScope?: (number | null) | Variant;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Elke onderwijsvariant (MijnLeerlijn, MijnMonti, MijnD, …) — branding, domein en terminologie.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  /**
   * Bijv. 'MijnMonti'.
   */
  name: string;
  /**
   * Gebruikt in de pad-gebaseerde fallback-route, bijv. 'mijnmonti'.
   */
  slug: string;
  status: 'concept' | 'actief' | 'gearchiveerd';
  /**
   * Bijv. 'algemeen', 'montessori', 'dalton', 'vrijeschool'.
   */
  educationType: string;
  domain: {
    type: 'custom_domain' | 'subdomain' | 'slug_path';
    value: string;
    domainStatus: 'slug_path' | 'subdomain' | 'custom_domain';
  };
  branding: {
    logo?: (number | null) | Media;
    /**
     * Hexcode. Zolang isPlaceholder aan staat: erft het MijnLeerlijn-kleurenpalet, nooit een verzonnen kleur — zie docs/MULTI-VARIANT-STRATEGY.md §Placeholder-branding-regels.
     */
    accentColor: string;
    productName: string;
    tagline: string;
    /**
     * Blijft aan totdat een beheerder definitieve merkbestanden heeft geüpload en dit bewust uitzet.
     */
    isPlaceholder?: boolean | null;
  };
  /**
   * Centraal begrip → variant-begrip. Wordt automatisch toegepast op alle centrale tekst binnen deze variant.
   */
  terminologyDictionary?:
    | {
        centralTerm: string;
        variantTerm: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optioneel — overschrijft het standaard helpdesk-adres voor deze variant.
   */
  contactEmail?: string | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Verplicht voor toegankelijkheid — beschrijft de afbeelding, nooit leeg.
   */
  altText: string;
  mediaType: 'afbeelding' | 'video' | 'download';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  /**
   * Naam van een Lucide-icoon, bijv. 'Target'.
   */
  icon: string;
  color: 'blauw' | 'groen' | 'oranje' | 'geel' | 'rood';
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * De centrale, enige-bron-van-waarheid handleidingen. Nooit per variant gekopieerd.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  summary: string;
  category: number | Category;
  tags?: string[] | null;
  /**
   * Leeg = relevant voor alle varianten (standaard). Ingevuld = dit centrale artikel is uitsluitend zichtbaar binnen deze variant(en) — geen kopie, alleen een zichtbaarheidsbeperking.
   */
  variantContext?: (number | Variant)[] | null;
  knowledgeType: 'product' | 'pedagogisch';
  articleStatus: 'concept' | 'in_review' | 'gepland' | 'gepubliceerd' | 'gearchiveerd';
  /**
   * Verplicht 'Goedgekeurd' voordat pedagogische content in de AI-index mag — uitsluitend door een beheerder te zetten. Zie docs/CONTENT-MODEL.md §Twee soorten kennis.
   */
  aiApprovalStatus: 'n.v.t.' | 'in_afwachting' | 'goedgekeurd';
  /**
   * Systeemveld voor de indexeerpijplijn — Fase 6.
   */
  embeddingStatus: 'pending' | 'indexed' | 'stale';
  publishedAt?: string | null;
  /**
   * Datum van laatste inhoudelijke wijziging — verplicht getoond bij bronvermelding.
   */
  lastContentUpdate: string;
  author?: (number | null) | User;
  sources?: (number | Source)[] | null;
  relatedArticles?: (number | Article)[] | null;
  sections: {
    title: string;
    blocks?:
      | (
          | {
              body: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
              blockName?: string | null;
              blockType: 'tekst';
            }
          | {
              body: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'genummerde_stap';
            }
          | {
              media: number | Media;
              caption?: string | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'afbeelding';
            }
          | {
              body: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'waarschuwing';
            }
          | {
              body: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'tip';
            }
          | {
              url: string;
              caption?: string | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'video';
            }
          | {
              media: number | Media;
              label: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'download';
            }
          | {
              body: string;
              prefilledSubject?: string | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'contact_doorverwijzing';
            }
        )[]
      | null;
    id?: string | null;
  }[];
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: number;
  title: string;
  type: 'interne_handleiding' | 'externe_link' | 'document' | 'onderzoek' | 'overig';
  /**
   * Voor een externe link of online publicatie.
   */
  url?: string | null;
  /**
   * Voor een geüpload document.
   */
  file?: (number | null) | Media;
  publisher?: string | null;
  publishedDate?: string | null;
  reliability: 'hoog' | 'gemiddeld' | 'laag';
  /**
   * Leeg = relevant voor alle varianten. Ingevuld = alleen relevant binnen deze variant(en).
   */
  variantContext?: (number | Variant)[] | null;
  usageRights?: string | null;
  internalStatus: 'concept' | 'goedgekeurd' | 'verouderd';
  updatedAt: string;
  createdAt: string;
}
/**
 * Variant-specifieke aanvullingen, vervangingen of uitsluitingen op de centrale artikelboom.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variant-overrides".
 */
export interface VariantOverride {
  id: number;
  variant: number | Variant;
  /**
   * Het centrale artikel waarbinnen dit inhaakt.
   */
  targetArticle: number | Article;
  targetType: 'article' | 'section' | 'block';
  /**
   * Gelijk aan targetArticle's ID wanneer Niveau = Artikel; anders de ID van de specifieke sectie of het specifieke blok binnen dat artikel.
   */
  targetId: string;
  action: 'onveranderd' | 'aanvullen' | 'vervangen' | 'verbergen' | 'ander_medium' | 'invoegen_voor' | 'invoegen_na';
  /**
   * Vervangende/aanvullende/ingevoegde blokinhoud, of een media-referentie bij 'Ander medium'. Leeg bij 'Onveranderd' of 'Verbergen'.
   */
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Standaard aan. Uitzetten wanneer dit element al de juiste variant-terminologie bevat.
   */
  termOverridesApplied?: boolean | null;
  status: 'concept' | 'gepubliceerd';
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Redactioneel gekozen recente wijzigingen, getoond op de homepage en /updates.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "updates".
 */
export interface Update {
  id: number;
  article: number | Article;
  badge: 'Nieuw' | 'Bijgewerkt';
  date: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Inzendingen van het contactformulier. Aanmaken kan alleen via de eigen API-route.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  teacherName: string;
  schoolName: string;
  email: string;
  requestType: string;
  subject: string;
  problemDescription: string;
  expected?: string | null;
  actual?: string | null;
  pageUrl?: string | null;
  variant?: (number | null) | Variant;
  helpCenterUrl?: string | null;
  submittedAt: string;
  /**
   * Alleen een grove categorie (bv. 'Chrome op desktop') — nooit een volledige user-agent.
   */
  deviceInfo?: string | null;
  status: 'nieuw' | 'in_behandeling' | 'afgehandeld';
  /**
   * Bestanden staan privé in Vercel Blob. Downloaden genereert een kortlevende signed URL.
   */
  attachments?:
    | {
        storageKey: string;
        filename: string;
        mimeType: string;
        sizeBytes: number;
        uploadedAt: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Ja/nee-feedback van bezoekers op AI-antwoorden. Aanmaken kan alleen via de eigen API-route.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "answer-feedback".
 */
export interface AnswerFeedback {
  id: number;
  vraag: string;
  antwoordTekst: string;
  bronArtikelSlugs?: string[] | null;
  variant?: (number | null) | Variant;
  rating: 'nuttig' | 'niet_nuttig';
  pageUrl?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * Geïmporteerde Gmail-helpdesk-threads (alleen-lezen buiten de synchronisatie om).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-threads".
 */
export interface SupportThread {
  id: number;
  /**
   * Voorkomt dubbele import — zie lib/gmail/sync.ts.
   */
  gmailThreadId: string;
  subject?: string | null;
  /**
   * Unieke e-mailadressen uit van/aan/cc van alle berichten.
   */
  participants?: string[] | null;
  firstMessageAt?: string | null;
  lastMessageAt?: string | null;
  messageCount?: number | null;
  snippet?: string | null;
  messages?:
    | {
        gmailMessageId: string;
        from?: string | null;
        to?: string[] | null;
        cc?: string[] | null;
        sentAt?: string | null;
        subject?: string | null;
        /**
         * Platte tekst (HTML omgezet). Citaten/handtekeningen bewust niet agressief verwijderd.
         */
        bodyText?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Handmatig door een beheerder te zetten — de sync zelf wijzigt dit nooit.
   */
  status: 'new' | 'reviewed' | 'ignored' | 'processed';
  importedAt?: string | null;
  updatedFromGmailAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'variant-overrides';
        value: number | VariantOverride;
      } | null)
    | ({
        relationTo: 'sources';
        value: number | Source;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'updates';
        value: number | Update;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'answer-feedback';
        value: number | AnswerFeedback;
      } | null)
    | ({
        relationTo: 'support-threads';
        value: number | SupportThread;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  variantScope?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  educationType?: T;
  domain?:
    | T
    | {
        type?: T;
        value?: T;
        domainStatus?: T;
      };
  branding?:
    | T
    | {
        logo?: T;
        accentColor?: T;
        productName?: T;
        tagline?: T;
        isPlaceholder?: T;
      };
  terminologyDictionary?:
    | T
    | {
        centralTerm?: T;
        variantTerm?: T;
        id?: T;
      };
  contactEmail?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  icon?: T;
  color?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  category?: T;
  tags?: T;
  variantContext?: T;
  knowledgeType?: T;
  articleStatus?: T;
  aiApprovalStatus?: T;
  embeddingStatus?: T;
  publishedAt?: T;
  lastContentUpdate?: T;
  author?: T;
  sources?: T;
  relatedArticles?: T;
  sections?:
    | T
    | {
        title?: T;
        blocks?:
          | T
          | {
              tekst?:
                | T
                | {
                    body?: T;
                    id?: T;
                    blockName?: T;
                  };
              genummerde_stap?:
                | T
                | {
                    body?: T;
                    id?: T;
                    blockName?: T;
                  };
              afbeelding?:
                | T
                | {
                    media?: T;
                    caption?: T;
                    id?: T;
                    blockName?: T;
                  };
              waarschuwing?:
                | T
                | {
                    body?: T;
                    id?: T;
                    blockName?: T;
                  };
              tip?:
                | T
                | {
                    body?: T;
                    id?: T;
                    blockName?: T;
                  };
              video?:
                | T
                | {
                    url?: T;
                    caption?: T;
                    id?: T;
                    blockName?: T;
                  };
              download?:
                | T
                | {
                    media?: T;
                    label?: T;
                    id?: T;
                    blockName?: T;
                  };
              contact_doorverwijzing?:
                | T
                | {
                    body?: T;
                    prefilledSubject?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variant-overrides_select".
 */
export interface VariantOverridesSelect<T extends boolean = true> {
  variant?: T;
  targetArticle?: T;
  targetType?: T;
  targetId?: T;
  action?: T;
  payload?: T;
  termOverridesApplied?: T;
  status?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  url?: T;
  file?: T;
  publisher?: T;
  publishedDate?: T;
  reliability?: T;
  variantContext?: T;
  usageRights?: T;
  internalStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  altText?: T;
  mediaType?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "updates_select".
 */
export interface UpdatesSelect<T extends boolean = true> {
  article?: T;
  badge?: T;
  date?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  teacherName?: T;
  schoolName?: T;
  email?: T;
  requestType?: T;
  subject?: T;
  problemDescription?: T;
  expected?: T;
  actual?: T;
  pageUrl?: T;
  variant?: T;
  helpCenterUrl?: T;
  submittedAt?: T;
  deviceInfo?: T;
  status?: T;
  attachments?:
    | T
    | {
        storageKey?: T;
        filename?: T;
        mimeType?: T;
        sizeBytes?: T;
        uploadedAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "answer-feedback_select".
 */
export interface AnswerFeedbackSelect<T extends boolean = true> {
  vraag?: T;
  antwoordTekst?: T;
  bronArtikelSlugs?: T;
  variant?: T;
  rating?: T;
  pageUrl?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-threads_select".
 */
export interface SupportThreadsSelect<T extends boolean = true> {
  gmailThreadId?: T;
  subject?: T;
  participants?: T;
  firstMessageAt?: T;
  lastMessageAt?: T;
  messageCount?: T;
  snippet?: T;
  messages?:
    | T
    | {
        gmailMessageId?: T;
        from?: T;
        to?: T;
        cc?: T;
        sentAt?: T;
        subject?: T;
        bodyText?: T;
        id?: T;
      };
  status?: T;
  importedAt?: T;
  updatedFromGmailAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Gmail-helpdeskkoppeling (alleen-lezen toegang). Koppelen/herkoppelen: log in op /admin en open /api/gmail/oauth/start in dezelfde browser.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gmail-connection".
 */
export interface GmailConnection {
  id: number;
  /**
   * Succesvol gekoppeld helpdesk-adres.
   */
  emailAddress?: string | null;
  /**
   * AES-256-GCM-ciphertext — nooit de platte token.
   */
  encryptedAccessToken?: string | null;
  /**
   * AES-256-GCM-ciphertext — nooit de platte token.
   */
  encryptedRefreshToken?: string | null;
  tokenExpiresAt?: string | null;
  scopes?: string[] | null;
  connectedAt?: string | null;
  /**
   * Wordt gezet door elke synchronisatieronde, ongeacht het resultaat per thread.
   */
  lastSyncAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gmail-connection_select".
 */
export interface GmailConnectionSelect<T extends boolean = true> {
  emailAddress?: T;
  encryptedAccessToken?: T;
  encryptedRefreshToken?: T;
  tokenExpiresAt?: T;
  scopes?: T;
  connectedAt?: T;
  lastSyncAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'articles';
      value: number | Article;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}