/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    variants: Variant;
    categories: Category;
    articles: Article;
    'variant-overrides': VariantOverride;
    sources: Source;
    media: Media;
    updates: Update;
    'contact-submissions': ContactSubmission;
    'answer-feedback': AnswerFeedback;
    'support-threads': SupportThread;
    'knowledge-drafts': KnowledgeDraft;
    'knowledge-sources': KnowledgeSource;
    handleidingen: Handleidingen;
    'kennisbasis-onderwerpen': KennisbasisOnderwerpen;
    'assistant-conversations': AssistantConversation;
    'assistant-eval-questions': AssistantEvalQuestion;
    'assistant-eval-runs': AssistantEvalRun;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'variant-overrides': VariantOverridesSelect<false> | VariantOverridesSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    updates: UpdatesSelect<false> | UpdatesSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'answer-feedback': AnswerFeedbackSelect<false> | AnswerFeedbackSelect<true>;
    'support-threads': SupportThreadsSelect<false> | SupportThreadsSelect<true>;
    'knowledge-drafts': KnowledgeDraftsSelect<false> | KnowledgeDraftsSelect<true>;
    'knowledge-sources': KnowledgeSourcesSelect<false> | KnowledgeSourcesSelect<true>;
    handleidingen: HandleidingenSelect<false> | HandleidingenSelect<true>;
    'kennisbasis-onderwerpen': KennisbasisOnderwerpenSelect<false> | KennisbasisOnderwerpenSelect<true>;
    'assistant-conversations': AssistantConversationsSelect<false> | AssistantConversationsSelect<true>;
    'assistant-eval-questions': AssistantEvalQuestionsSelect<false> | AssistantEvalQuestionsSelect<true>;
    'assistant-eval-runs': AssistantEvalRunsSelect<false> | AssistantEvalRunsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'gmail-connection': GmailConnection;
    'knowledge-search': KnowledgeSearch;
    'assistant-eval': AssistantEval;
    'helpdesk-voorbeeldvragen': HelpdeskVoorbeeldvragen;
  };
  globalsSelect: {
    'gmail-connection': GmailConnectionSelect<false> | GmailConnectionSelect<true>;
    'knowledge-search': KnowledgeSearchSelect<false> | KnowledgeSearchSelect<true>;
    'assistant-eval': AssistantEvalSelect<false> | AssistantEvalSelect<true>;
    'helpdesk-voorbeeldvragen': HelpdeskVoorbeeldvragenSelect<false> | HelpdeskVoorbeeldvragenSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Redacteuren en beheerders van de beheeromgeving.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Beheerder kan alles inclusief varianten, rollen en AI-goedkeuring. Redacteur is beperkter.
   */
  role: 'admin' | 'editor';
  /**
   * Leeg = centrale redacteur (mag centrale artikelen schrijven). Ingevuld = variant-redacteur (mag uitsluitend afwijkingen voor déze variant schrijven, nooit de centrale boom). Zie docs/CONTENT-MODEL.md.
   */
  variantScope?: (number | null) | Variant;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Elke onderwijsvariant (MijnLeerlijn, MijnMonti, MijnD, …) — branding, domein en terminologie.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  /**
   * Bijv. 'MijnMonti'.
   */
  name: string;
  /**
   * Gebruikt in de pad-gebaseerde fallback-route, bijv. 'mijnmonti'.
   */
  slug: string;
  status: 'concept' | 'actief' | 'gearchiveerd';
  /**
   * Bijv. 'algemeen', 'montessori', 'dalton', 'vrijeschool'.
   */
  educationType: string;
  domain: {
    type: 'custom_domain' | 'subdomain' | 'slug_path';
    value: string;
    domainStatus: 'slug_path' | 'subdomain' | 'custom_domain';
  };
  branding: {
    logo?: (number | null) | Media;
    /**
     * Hexcode. Zolang isPlaceholder aan staat: erft het MijnLeerlijn-kleurenpalet, nooit een verzonnen kleur — zie docs/MULTI-VARIANT-STRATEGY.md §Placeholder-branding-regels.
     */
    accentColor: string;
    productName: string;
    tagline: string;
    /**
     * Blijft aan totdat een beheerder definitieve merkbestanden heeft geüpload en dit bewust uitzet.
     */
    isPlaceholder?: boolean | null;
  };
  /**
   * Centraal begrip → variant-begrip. Wordt automatisch toegepast op alle centrale tekst binnen deze variant.
   */
  terminologyDictionary?:
    | {
        centralTerm: string;
        variantTerm: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optioneel — overschrijft het standaard helpdesk-adres voor deze variant.
   */
  contactEmail?: string | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Verplicht voor toegankelijkheid — beschrijft de afbeelding, nooit leeg.
   */
  altText: string;
  mediaType: 'afbeelding' | 'video' | 'download';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  /**
   * Naam van een Lucide-icoon, bijv. 'Target'.
   */
  icon: string;
  color: 'blauw' | 'groen' | 'oranje' | 'geel' | 'rood';
  description: string;
  /**
   * Bepaalt de volgorde van categorieën op de publieke downloadpagina. Laag = eerder. Leeg = alfabetisch, onderaan. Wordt beheerd via de 'Downloadcategorieën'-pagina in het menu.
   */
  volgorde?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * De centrale, enige-bron-van-waarheid handleidingen. Nooit per variant gekopieerd.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  summary: string;
  category: number | Category;
  tags?: string[] | null;
  /**
   * Leeg = relevant voor alle varianten (standaard). Ingevuld = dit centrale artikel is uitsluitend zichtbaar binnen deze variant(en) — geen kopie, alleen een zichtbaarheidsbeperking.
   */
  variantContext?: (number | Variant)[] | null;
  knowledgeType: 'product' | 'pedagogisch';
  articleStatus: 'concept' | 'in_review' | 'gepland' | 'gepubliceerd' | 'gearchiveerd';
  /**
   * Verplicht 'Goedgekeurd' voordat pedagogische content in de AI-index mag — uitsluitend door een beheerder te zetten. Zie docs/CONTENT-MODEL.md §Twee soorten kennis.
   */
  aiApprovalStatus: 'n.v.t.' | 'in_afwachting' | 'goedgekeurd';
  embeddingStatus: 'pending' | 'indexed' | 'stale';
  embeddedAt?: string | null;
  embeddingModel?: string | null;
  embeddingTextHash?: string | null;
  /**
   * Tijdelijke ruwe vectoropslag — zie payload/collections/KnowledgeSources.ts.
   */
  embedding?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  publishedAt?: string | null;
  /**
   * Datum van laatste inhoudelijke wijziging — verplicht getoond bij bronvermelding.
   */
  lastContentUpdate: string;
  author?: (number | null) | User;
  sources?: (number | Source)[] | null;
  relatedArticles?: (number | Article)[] | null;
  sections: {
    title: string;
    blocks?:
      | (
          | {
              body: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
              blockName?: string | null;
              blockType: 'tekst';
            }
          | {
              body: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'genummerde_stap';
            }
          | {
              media: number | Media;
              caption?: string | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'afbeelding';
            }
          | {
              body: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'waarschuwing';
            }
          | {
              body: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'tip';
            }
          | {
              url: string;
              caption?: string | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'video';
            }
          | {
              media: number | Media;
              label: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'download';
            }
          | {
              body: string;
              prefilledSubject?: string | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'contact_doorverwijzing';
            }
        )[]
      | null;
    id?: string | null;
  }[];
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: number;
  title: string;
  type: 'interne_handleiding' | 'externe_link' | 'document' | 'onderzoek' | 'overig';
  /**
   * Voor een externe link of online publicatie.
   */
  url?: string | null;
  /**
   * Voor een geüpload document.
   */
  file?: (number | null) | Media;
  publisher?: string | null;
  publishedDate?: string | null;
  reliability: 'hoog' | 'gemiddeld' | 'laag';
  /**
   * Leeg = relevant voor alle varianten. Ingevuld = alleen relevant binnen deze variant(en).
   */
  variantContext?: (number | Variant)[] | null;
  usageRights?: string | null;
  internalStatus: 'concept' | 'goedgekeurd' | 'verouderd';
  updatedAt: string;
  createdAt: string;
}
/**
 * Variant-specifieke aanvullingen, vervangingen of uitsluitingen op de centrale artikelboom.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variant-overrides".
 */
export interface VariantOverride {
  id: number;
  variant: number | Variant;
  /**
   * Het centrale artikel waarbinnen dit inhaakt.
   */
  targetArticle: number | Article;
  targetType: 'article' | 'section' | 'block';
  /**
   * Gelijk aan targetArticle's ID wanneer Niveau = Artikel; anders de ID van de specifieke sectie of het specifieke blok binnen dat artikel.
   */
  targetId: string;
  action: 'onveranderd' | 'aanvullen' | 'vervangen' | 'verbergen' | 'ander_medium' | 'invoegen_voor' | 'invoegen_na';
  /**
   * Vervangende/aanvullende/ingevoegde blokinhoud, of een media-referentie bij 'Ander medium'. Leeg bij 'Onveranderd' of 'Verbergen'.
   */
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Standaard aan. Uitzetten wanneer dit element al de juiste variant-terminologie bevat.
   */
  termOverridesApplied?: boolean | null;
  status: 'concept' | 'gepubliceerd';
  editedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Redactioneel gekozen recente wijzigingen, getoond op de homepage en /updates.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "updates".
 */
export interface Update {
  id: number;
  article: number | Article;
  badge: 'Nieuw' | 'Bijgewerkt';
  date: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Inzendingen van het contactformulier. Aanmaken kan alleen via de eigen API-route.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  teacherName: string;
  schoolName: string;
  email: string;
  requestType: string;
  subject: string;
  problemDescription: string;
  expected?: string | null;
  actual?: string | null;
  pageUrl?: string | null;
  variant?: (number | null) | Variant;
  helpCenterUrl?: string | null;
  submittedAt: string;
  /**
   * Alleen een grove categorie (bv. 'Chrome op desktop') — nooit een volledige user-agent.
   */
  deviceInfo?: string | null;
  status: 'nieuw' | 'in_behandeling' | 'afgehandeld';
  /**
   * Bestanden staan privé in Vercel Blob. Downloaden genereert een kortlevende signed URL.
   */
  attachments?:
    | {
        storageKey: string;
        filename: string;
        mimeType: string;
        sizeBytes: number;
        uploadedAt: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Ja/nee-feedback van bezoekers op AI-antwoorden. Aanmaken kan alleen via de eigen API-route.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "answer-feedback".
 */
export interface AnswerFeedback {
  id: number;
  vraag: string;
  antwoordTekst: string;
  bronArtikelSlugs?: string[] | null;
  variant?: (number | null) | Variant;
  rating: 'nuttig' | 'niet_nuttig';
  pageUrl?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * Geïmporteerde Gmail-helpdesk-threads (alleen-lezen buiten de synchronisatie om).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-threads".
 */
export interface SupportThread {
  id: number;
  /**
   * Voorkomt dubbele import — zie lib/gmail/sync.ts.
   */
  gmailThreadId: string;
  subject?: string | null;
  /**
   * Unieke e-mailadressen uit van/aan/cc van alle berichten.
   */
  participants?: string[] | null;
  firstMessageAt?: string | null;
  lastMessageAt?: string | null;
  messageCount?: number | null;
  snippet?: string | null;
  messages?:
    | {
        gmailMessageId: string;
        from?: string | null;
        to?: string[] | null;
        cc?: string[] | null;
        sentAt?: string | null;
        subject?: string | null;
        /**
         * Platte tekst (HTML omgezet). Citaten/handtekeningen bewust niet agressief verwijderd.
         */
        bodyText?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Handmatig door een beheerder te zetten — de sync zelf wijzigt dit nooit.
   */
  status: 'new' | 'reviewed' | 'ignored' | 'processed';
  importedAt?: string | null;
  updatedFromGmailAt?: string | null;
  /**
   * 'Genegeerd' = de AI vond de thread te specifiek, onduidelijk of onopgelost (reden in aiAnalysisError) — geen concept aangemaakt. 'Mislukt' = technische fout tijdens analyse, nooit ten onrechte op 'Geanalyseerd' gezet.
   */
  aiAnalysisStatus: 'not-analyzed' | 'analyzing' | 'analyzed' | 'failed' | 'ignored';
  /**
   * Alleen technische foutmeldingen of AI-redenering — nooit berichtinhoud of persoonsgegevens.
   */
  aiAnalysisError?: string | null;
  /**
   * Concepten die (mede) uit deze thread zijn ontstaan.
   */
  knowledgeDrafts?: (number | KnowledgeDraft)[] | null;
  analyzedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * AI-conceptkennisartikelen uit Gmail-helpdeskthreads. Aanmaken kan alleen via de synchronisatieroute; hier uitsluitend bekijken, aanpassen, goedkeuren of afkeuren.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-drafts".
 */
export interface KnowledgeDraft {
  id: number;
  title: string;
  question: string;
  shortAnswer: string;
  fullAnswer: string;
  steps?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  category?: string | null;
  keywords?: string[] | null;
  /**
   * Alle Gmail-threads die tot dit concept hebben bijgedragen.
   */
  sourceThreads?: (number | SupportThread)[] | null;
  /**
   * Handleidingen/video's/release notes/etc. die dit concept onderbouwen — automatisch, deterministisch gekoppeld op trefwoordoverlap (lib/knowledge/link-drafts.ts), nooit door de AI zelf 'besloten'.
   */
  knowledgeSources?: (number | KnowledgeSource)[] | null;
  confidenceScore: number;
  confidenceExplanation?: string | null;
  /**
   * Is deze kennis nuttig voor andere MijnLeerlijn-gebruikers, niet alleen deze afzender?
   */
  isGeneralKnowledge?: boolean | null;
  /**
   * Stond er in de brontekst iets klant-/leerling-/schoolspecifieks? Het concept zelf hoort dat nooit te bevatten (zie fullAnswer/shortAnswer) — dit vinkje is alleen ter waarschuwing bij het beoordelen.
   */
  customerSpecificInformationFound?: boolean | null;
  customerSpecificInformationExplanation?: string | null;
  status: 'new' | 'review' | 'approved' | 'rejected' | 'published';
  aiModel?: string | null;
  aiAnalyzedAt?: string | null;
  /**
   * Vrije notities van de beheerder bij het goed-/afkeuren.
   */
  reviewNotes?: string | null;
  embeddingStatus: 'pending' | 'indexed' | 'stale';
  embeddedAt?: string | null;
  embeddingModel?: string | null;
  embeddingTextHash?: string | null;
  /**
   * Tijdelijke ruwe vectoropslag — zie payload/collections/KnowledgeSources.ts.
   */
  embedding?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kennisbronnen voor de AI (PDF's, video's, websites, release notes, handleidingen, FAQ's, interne documenten). Toevoegen via 'Create new'; indexeren via de knop hierboven in de lijst.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-sources".
 */
export interface KnowledgeSource {
  id: number;
  title: string;
  type: 'pdf' | 'video' | 'website' | 'release_notes' | 'handleiding' | 'faq' | 'intern_document';
  /**
   * Kerninhoud: belangrijkste handleidingen met praktische instructies. Aanvullende inhoud: uitsluitend als aanvulling. Achtergrondinformatie: laagste zoekprioriteit. Wordt nog niet gebruikt door de zoeklogica zelf.
   */
  priority: 'core' | 'secondary' | 'reference';
  /**
   * Verplicht voor type PDF — het document dat de AI uitleest.
   */
  file?: (number | null) | Media;
  /**
   * Alleen bronnen die hier aangevinkt zijn, verschijnen voor bezoekers in de 'Handleidingen'-sidebar en in de bronvermelding onder een AI-antwoord. Heeft geen invloed op wat de AI intern mag gebruiken om te antwoorden.
   */
  zichtbaar?: boolean | null;
  /**
   * Bepaalt onder welke uitklapbare categorie deze bron in de sidebar verschijnt.
   */
  categorie?: (number | null) | Category;
  /**
   * Laag = hoger in de lijst binnen de categorie. Leeg = alfabetisch op titel, onderaan.
   */
  volgorde?: number | null;
  /**
   * Voor alle typen behalve PDF: link naar de video, website, release notes, handleiding, FAQ of het interne document. Alternatief voor 'Directe inhoud' hieronder — vul één van beide in.
   */
  url?: string | null;
  /**
   * Alternatief voor URL: tekst die niet online staat rechtstreeks plakken (bv. een intern achtergronddocument). Gevuld = deze tekst wordt gebruikt, er wordt dan niet van de URL gefetcht.
   */
  content?: string | null;
  /**
   * Rol van deze bron bij het oplossen van een conflict tussen bronnen. Leeg = automatisch afgeleid van het type. Zie het commentaar in lib/embeddings/similarity-search.ts voor de precieze conflictvolgorde.
   */
  purpose?: ('background-model' | 'manual' | 'release-note' | 'faq' | 'support') | null;
  /**
   * Leeg = centraal, relevant voor alle varianten (standaard). Ingevuld = deze bron is uitsluitend bedoeld voor de gekozen variant(en). Nog niet gebruikt door de retrieval zelf — puur classificatie, zie het commentaar hiernaast.
   */
  variantContext?: (number | Variant)[] | null;
  /**
   * Alleen voor automatisch gesynchroniseerde bronnen — zie lib/knowledge/sync-manuals.ts.
   */
  sourceFilePath?: string | null;
  sourceFileHash?: string | null;
  description?: string | null;
  tags?: string[] | null;
  /**
   * Voor video's: handmatig plakken, of automatisch opgehaald als de video-URL rechtstreeks naar platte tekst/VTT/SRT verwijst (zie lib/knowledge/video.ts). Blijft leeg als ophalen niet eenvoudig mogelijk was.
   */
  transcript?: string | null;
  /**
   * Alleen voor PDF's — automatisch herkend en samengevat door de AI.
   */
  chapters?:
    | {
        title: string;
        summary: string;
        order: number;
        embedding?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        embeddingTextHash?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Wordt uitsluitend gezet door de indexeerroute — nooit handmatig aanpassen.
   */
  status: 'new' | 'indexing' | 'indexed' | 'error';
  /**
   * Alleen gevuld bij status 'Fout' — technische reden, nooit brontekst of persoonsgegevens.
   */
  indexError?: string | null;
  aiSummary?: string | null;
  aiKeywords?: string[] | null;
  /**
   * Vrije tekst, net als KnowledgeDrafts.category — nog geen koppeling aan de echte taxonomie.
   */
  aiCategory?: string | null;
  aiModel?: string | null;
  aiIndexedAt?: string | null;
  /**
   * Concepten die deze bron als onderbouwing gebruiken — automatisch gekoppeld bij het indexeren.
   */
  knowledgeDrafts?: (number | KnowledgeDraft)[] | null;
  /**
   * Wordt gezet door POST /api/knowledge/embed (lib/embeddings/process-embedding.ts) — LET OP: dit is iets anders dan het veld 'Status' hierboven (dat gaat over de AI-samenvatting uit Sprint 3, niet over embeddings).
   */
  embeddingStatus: 'pending' | 'indexed' | 'stale';
  embeddedAt?: string | null;
  /**
   * Bv. text-embedding-3-small — zie services/ai-client.ts.
   */
  embeddingModel?: string | null;
  /**
   * Sha256 van titel+samenvatting+trefwoorden+categorie — bepaalt of herembedden nodig is.
   */
  embeddingTextHash?: string | null;
  /**
   * Tijdelijke ruwe vectoropslag (JSON-array) zolang er geen externe vectorstore/pgvector is — zie het commentaar bovenaan dit bestand. Nooit rechtstreeks tonen/bewerken in de admin-UI.
   */
  embedding?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Handleidingen opgebouwd uit losse stappen met tekst en afbeeldingen — de opvolger van PDF-handleidingen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "handleidingen".
 */
export interface Handleidingen {
  id: number;
  internTitel: string;
  titel: string;
  /**
   * Voor de publieke URL: /handleidingen/{slug}
   */
  slug: string;
  korteOmschrijving: string;
  categorie?: (number | null) | Category;
  /**
   * Leeg = relevant voor alle varianten (standaard).
   */
  variantContext?: (number | Variant)[] | null;
  status: 'concept' | 'gepubliceerd' | 'gearchiveerd';
  /**
   * Alleen bronnen die hier aangevinkt zijn, verschijnen voor bezoekers in de 'Handleidingen'-sidebar. Heeft geen invloed op wat de AI intern mag gebruiken om te antwoorden.
   */
  zichtbaarInSidebar?: boolean | null;
  /**
   * Laag = hoger in de lijst binnen de categorie. Leeg = alfabetisch op titel, onderaan.
   */
  volgorde?: number | null;
  zoekwoorden?: string[] | null;
  laatstBijgewerkt?: string | null;
  /**
   * Optioneel: een bestaande PDF-handleiding die dit vervangt/aanvult. Toont een downloadlink op de publieke pagina. Geen automatische import — alleen een koppeling.
   */
  legacyBron?: (number | null) | KnowledgeSource;
  /**
   * Eenvoudige teller, geen volwaardig versiebeheer — wordt op 1 gezet bij de eerste publicatie en daarna opgehoogd bij elke volgende publicatie. Leeg zolang de handleiding nog nooit gepubliceerd is.
   */
  versie?: number | null;
  gepubliceerdOp?: string | null;
  gepubliceerdDoor?: (number | null) | User;
  /**
   * Sleep aan de rijen om te herordenen. Elke stap krijgt automatisch een vaste, permanente id die nooit verandert door herordenen of een titelwijziging — de AI verwijst naar die id, niet naar de titel.
   */
  stappen?:
    | {
        titel: string;
        /**
         * Beperkte opmaak: vet, lijst, link. Wordt automatisch naar platte tekst omgezet voor de AI.
         */
        uitleg: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        /**
         * Screenshots bij deze stap. Bewust 'media' genoemd (niet 'afbeeldingen') zodat hier later ook video bij kan — voor nu wordt alleen een afbeelding ondersteund.
         */
        media?:
          | {
              bestand: number | Media;
              onderschrift?: string | null;
              id?: string | null;
            }[]
          | null;
        waarschuwing?: string | null;
        tip?: string | null;
        /**
         * Bijv. 'Beheer > Hoofdgebiedprofielen' of 'Nieuw profiel'.
         */
        knopOfSchermnaam?: string | null;
        zoekwoorden?: string[] | null;
        /**
         * Leeg = relevant voor alle varianten.
         */
        variantContext?: (number | Variant)[] | null;
        /**
         * Nooit publiek zichtbaar en nooit gebruikt in AI-antwoorden.
         */
        interneNotitie?: string | null;
        /**
         * Verbergt deze stap op de publieke pagina en in AI-antwoorden, zonder hem te verwijderen.
         */
        verborgen?: boolean | null;
        embeddingStatus?: ('pending' | 'indexed' | 'stale') | null;
        embeddingTextHash?: string | null;
        embedding?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Wordt automatisch gezet bij publiceren — nooit handmatig aanpassen.
   */
  embeddingStatus: 'pending' | 'indexed' | 'stale';
  embeddedAt?: string | null;
  embeddingModel?: string | null;
  embeddingTextHash?: string | null;
  embedding?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Functiegerichte term- en synoniemkennis voor intentiebepaling door de AI Helpdesk — een ANDER brontype dan het narratieve achtergrondverhaal (dat blijft apart bestaan als kennisbron). Bepaalt welke MijnLeerlijn-functie een leerkracht bedoelt, vóórdat er naar een handleiding gezocht wordt.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kennisbasis-onderwerpen".
 */
export interface KennisbasisOnderwerpen {
  id: number;
  /**
   * Korte interne titel, bv. 'Doelen koppelen aan één leerling'.
   */
  onderwerp: string;
  doel?: string | null;
  /**
   * Wordt als zoekvraag gebruikt zodra dit onderwerp herkend is — i.p.v. de letterlijke formulering van de gebruiker.
   */
  officieleTerm: string;
  /**
   * Bv. 'doelen', 'leerdoelen', 'leerling', 'kind', 'koppelen', 'toewijzen'.
   */
  synoniemen?: string[] | null;
  /**
   * Echte voorbeeldformuleringen — sterk signaal voor de intentiebepaling.
   */
  voorbeeldvragen?: string[] | null;
  /**
   * Alleen gebruikt door de AI om de intentie te bepalen — nooit rechtstreeks aan de gebruiker getoond.
   */
  toelichting?: string | null;
  /**
   * Structured handleidingen én/of PDF-bronnen die dit onderwerp uitvoeren. Polymorf omdat lang niet elk onderwerp al een structured handleiding heeft.
   */
  gekoppeldeHandleidingen?:
    | (
        | {
            relationTo: 'handleidingen';
            value: number | Handleidingen;
          }
        | {
            relationTo: 'knowledge-sources';
            value: number | KnowledgeSource;
          }
      )[]
    | null;
  /**
   * Als dit onderwerp met een ander onderwerp verward kan worden: de vraag die de assistent moet stellen om dat te verduidelijken, bv. 'Wil je doelen aan één leerling koppelen, of een doelenset aan meerdere leerlingen?'. Wordt letterlijk gebruikt als hij is ingevuld, i.p.v. dat de AI er zelf een verzint.
   */
  verduidelijkingsvraag?: string | null;
  /**
   * Tie-break wanneer meerdere onderwerpen plausibel lijken. Hoger = eerder gekozen.
   */
  prioriteit?: number | null;
  /**
   * Alleen 'Gepubliceerd' onderwerpen doen mee in de intentiebepaling.
   */
  status: 'concept' | 'gepubliceerd';
  updatedAt: string;
  createdAt: string;
}
/**
 * Logboek van vraag/antwoord-uitwisselingen met de AI-assistent (/assistant én de publieke helpdesk-homepage).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assistant-conversations".
 */
export interface AssistantConversation {
  id: number;
  source: 'assistant' | 'helpdesk';
  question: string;
  /**
   * False = 'Dat weet ik niet' — te weinig/geen betrouwbare bron gevonden.
   */
  hasAnswer: boolean;
  answer: string;
  reasoning?: string | null;
  /**
   * Retrieval-score van de beste bron — geen zelfinschatting van het model.
   */
  confidence: number;
  sources?:
    | {
        label: string;
        refCollection: string;
        refId: number;
        title: string;
        chapterTitle?: string | null;
        similarity: number;
        url: string;
        id?: string | null;
      }[]
    | null;
  steps?:
    | {
        handleidingId: number;
        stepId: string;
        stepNummer: number;
        id?: string | null;
      }[]
    | null;
  model?: string | null;
  inputTokens?: number | null;
  outputTokens?: number | null;
  totalTokens?: number | null;
  answerTimeMs?: number | null;
  feedbackRating: 'geen' | 'nuttig' | 'niet_nuttig';
  feedbackMissing?: string | null;
  /**
   * Leeg bij een anonieme vraag via de publieke helpdesk-homepage (source: 'helpdesk').
   */
  user?: (number | null) | User;
  /**
   * Alleen gezet als dit een vervolg is op een eerdere verduidelijkingsvraag.
   */
  previousQuestion?: string | null;
  intentieType?: ('opgelost' | 'onduidelijk' | 'geen-match') | null;
  kennisbasisOnderwerp?: (number | null) | KennisbasisOnderwerpen;
  /**
   * Alle onderwerpen die de intentiebepaling overwoog, niet alleen het gekozen onderwerp.
   */
  kennisbasisKandidaten?: (number | KennisbasisOnderwerpen)[] | null;
  gebruikteOfficieleTerm?: string | null;
  /**
   * Best-effort: welke synoniem/formulering de AI herkende. Puur informatief.
   */
  gebruikteSynoniem?: string | null;
  contactFormSubmitted?: boolean | null;
  geenHandleidingGevonden?: boolean | null;
  verbeterStatus: 'nieuw' | 'beoordeeld' | 'opgelost' | 'genegeerd';
  /**
   * Zie lib/assistant/versions.ts.
   */
  promptVersion?: string | null;
  retrievalVersion?: string | null;
  /**
   * Meest recente wijzigingsdatum onder de overwogen kennisbasis-onderwerpen.
   */
  kennisbasisVersion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Vaste testvragenset voor de chatbot-evaluatieomgeving (/admin/globals/assistant-eval). Zie payload/seed/eval-questions.ts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assistant-eval-questions".
 */
export interface AssistantEvalQuestion {
  id: number;
  question: string;
  /**
   * Bepaalt waarop deze vraag bedoeld is te testen — zie het commentaar bovenin payload/seed/eval-questions.ts voor de precieze definities.
   */
  category: 'feitelijk' | 'stap_voor_stap' | 'meerdere_routes' | 'onduidelijk' | 'onvoldoende_bron';
  /**
   * Optioneel: waarom deze vraag representatief is, of wat er lastig aan is.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Uitkomsten van chatbot-evaluatieruns (/admin/globals/assistant-eval) — diagnostiek + handmatige beoordeling per testvraag.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assistant-eval-runs".
 */
export interface AssistantEvalRun {
  id: number;
  /**
   * Leeg bij een losse, handmatig ingevoerde testvraag.
   */
  evalQuestion?: (number | null) | AssistantEvalQuestion;
  /**
   * Snapshot van de daadwerkelijk gebruikte vraagtekst.
   */
  question: string;
  /**
   * Zie lib/assistant/rewrite-query.ts.
   */
  rewrittenQuery: string;
  /**
   * "core", "core+secondary" of "core+secondary+reference" — zie searchKnowledgePhased.
   */
  retrievalFase: string;
  /**
   * Alles wat searchKnowledgePhased teruggaf, vóór antwoordgeneratie.
   */
  hits?:
    | {
        type: string;
        refId: number;
        title: string;
        chapterTitle?: string | null;
        similarity: number;
        priority?: string | null;
        bronrol?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Letterlijke prompt-context — zie contextItemsNaarPrompt().
   */
  contextText: string;
  hasAnswer: boolean;
  answer: string;
  reasoning?: string | null;
  confidence: number;
  /**
   * Leeg bij 'geen antwoord' — zelfde als in de echte assistent-UI.
   */
  sources?:
    | {
        label: string;
        refCollection: string;
        refId: number;
        title: string;
        chapterTitle?: string | null;
        similarity: number;
        url: string;
        id?: string | null;
      }[]
    | null;
  model?: string | null;
  /**
   * Handmatige beoordeling — wordt nooit automatisch bepaald.
   */
  verdict?: ('nog_niet_beoordeeld' | 'correct' | 'gedeeltelijk_correct' | 'incorrect') | null;
  /**
   * Vrij tekstveld: wat klopte niet, wat ontbrak, waarom deze beoordeling.
   */
  opmerkingen?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'variant-overrides';
        value: number | VariantOverride;
      } | null)
    | ({
        relationTo: 'sources';
        value: number | Source;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'updates';
        value: number | Update;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'answer-feedback';
        value: number | AnswerFeedback;
      } | null)
    | ({
        relationTo: 'support-threads';
        value: number | SupportThread;
      } | null)
    | ({
        relationTo: 'knowledge-drafts';
        value: number | KnowledgeDraft;
      } | null)
    | ({
        relationTo: 'knowledge-sources';
        value: number | KnowledgeSource;
      } | null)
    | ({
        relationTo: 'handleidingen';
        value: number | Handleidingen;
      } | null)
    | ({
        relationTo: 'kennisbasis-onderwerpen';
        value: number | KennisbasisOnderwerpen;
      } | null)
    | ({
        relationTo: 'assistant-conversations';
        value: number | AssistantConversation;
      } | null)
    | ({
        relationTo: 'assistant-eval-questions';
        value: number | AssistantEvalQuestion;
      } | null)
    | ({
        relationTo: 'assistant-eval-runs';
        value: number | AssistantEvalRun;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  variantScope?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  educationType?: T;
  domain?:
    | T
    | {
        type?: T;
        value?: T;
        domainStatus?: T;
      };
  branding?:
    | T
    | {
        logo?: T;
        accentColor?: T;
        productName?: T;
        tagline?: T;
        isPlaceholder?: T;
      };
  terminologyDictionary?:
    | T
    | {
        centralTerm?: T;
        variantTerm?: T;
        id?: T;
      };
  contactEmail?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  icon?: T;
  color?: T;
  description?: T;
  volgorde?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  category?: T;
  tags?: T;
  variantContext?: T;
  knowledgeType?: T;
  articleStatus?: T;
  aiApprovalStatus?: T;
  embeddingStatus?: T;
  embeddedAt?: T;
  embeddingModel?: T;
  embeddingTextHash?: T;
  embedding?: T;
  publishedAt?: T;
  lastContentUpdate?: T;
  author?: T;
  sources?: T;
  relatedArticles?: T;
  sections?:
    | T
    | {
        title?: T;
        blocks?:
          | T
          | {
              tekst?:
                | T
                | {
                    body?: T;
                    id?: T;
                    blockName?: T;
                  };
              genummerde_stap?:
                | T
                | {
                    body?: T;
                    id?: T;
                    blockName?: T;
                  };
              afbeelding?:
                | T
                | {
                    media?: T;
                    caption?: T;
                    id?: T;
                    blockName?: T;
                  };
              waarschuwing?:
                | T
                | {
                    body?: T;
                    id?: T;
                    blockName?: T;
                  };
              tip?:
                | T
                | {
                    body?: T;
                    id?: T;
                    blockName?: T;
                  };
              video?:
                | T
                | {
                    url?: T;
                    caption?: T;
                    id?: T;
                    blockName?: T;
                  };
              download?:
                | T
                | {
                    media?: T;
                    label?: T;
                    id?: T;
                    blockName?: T;
                  };
              contact_doorverwijzing?:
                | T
                | {
                    body?: T;
                    prefilledSubject?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variant-overrides_select".
 */
export interface VariantOverridesSelect<T extends boolean = true> {
  variant?: T;
  targetArticle?: T;
  targetType?: T;
  targetId?: T;
  action?: T;
  payload?: T;
  termOverridesApplied?: T;
  status?: T;
  editedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  url?: T;
  file?: T;
  publisher?: T;
  publishedDate?: T;
  reliability?: T;
  variantContext?: T;
  usageRights?: T;
  internalStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  altText?: T;
  mediaType?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "updates_select".
 */
export interface UpdatesSelect<T extends boolean = true> {
  article?: T;
  badge?: T;
  date?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  teacherName?: T;
  schoolName?: T;
  email?: T;
  requestType?: T;
  subject?: T;
  problemDescription?: T;
  expected?: T;
  actual?: T;
  pageUrl?: T;
  variant?: T;
  helpCenterUrl?: T;
  submittedAt?: T;
  deviceInfo?: T;
  status?: T;
  attachments?:
    | T
    | {
        storageKey?: T;
        filename?: T;
        mimeType?: T;
        sizeBytes?: T;
        uploadedAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "answer-feedback_select".
 */
export interface AnswerFeedbackSelect<T extends boolean = true> {
  vraag?: T;
  antwoordTekst?: T;
  bronArtikelSlugs?: T;
  variant?: T;
  rating?: T;
  pageUrl?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-threads_select".
 */
export interface SupportThreadsSelect<T extends boolean = true> {
  gmailThreadId?: T;
  subject?: T;
  participants?: T;
  firstMessageAt?: T;
  lastMessageAt?: T;
  messageCount?: T;
  snippet?: T;
  messages?:
    | T
    | {
        gmailMessageId?: T;
        from?: T;
        to?: T;
        cc?: T;
        sentAt?: T;
        subject?: T;
        bodyText?: T;
        id?: T;
      };
  status?: T;
  importedAt?: T;
  updatedFromGmailAt?: T;
  aiAnalysisStatus?: T;
  aiAnalysisError?: T;
  knowledgeDrafts?: T;
  analyzedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-drafts_select".
 */
export interface KnowledgeDraftsSelect<T extends boolean = true> {
  title?: T;
  question?: T;
  shortAnswer?: T;
  fullAnswer?: T;
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  category?: T;
  keywords?: T;
  sourceThreads?: T;
  knowledgeSources?: T;
  confidenceScore?: T;
  confidenceExplanation?: T;
  isGeneralKnowledge?: T;
  customerSpecificInformationFound?: T;
  customerSpecificInformationExplanation?: T;
  status?: T;
  aiModel?: T;
  aiAnalyzedAt?: T;
  reviewNotes?: T;
  embeddingStatus?: T;
  embeddedAt?: T;
  embeddingModel?: T;
  embeddingTextHash?: T;
  embedding?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-sources_select".
 */
export interface KnowledgeSourcesSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  priority?: T;
  file?: T;
  zichtbaar?: T;
  categorie?: T;
  volgorde?: T;
  url?: T;
  content?: T;
  purpose?: T;
  variantContext?: T;
  sourceFilePath?: T;
  sourceFileHash?: T;
  description?: T;
  tags?: T;
  transcript?: T;
  chapters?:
    | T
    | {
        title?: T;
        summary?: T;
        order?: T;
        embedding?: T;
        embeddingTextHash?: T;
        id?: T;
      };
  status?: T;
  indexError?: T;
  aiSummary?: T;
  aiKeywords?: T;
  aiCategory?: T;
  aiModel?: T;
  aiIndexedAt?: T;
  knowledgeDrafts?: T;
  embeddingStatus?: T;
  embeddedAt?: T;
  embeddingModel?: T;
  embeddingTextHash?: T;
  embedding?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "handleidingen_select".
 */
export interface HandleidingenSelect<T extends boolean = true> {
  internTitel?: T;
  titel?: T;
  slug?: T;
  korteOmschrijving?: T;
  categorie?: T;
  variantContext?: T;
  status?: T;
  zichtbaarInSidebar?: T;
  volgorde?: T;
  zoekwoorden?: T;
  laatstBijgewerkt?: T;
  legacyBron?: T;
  versie?: T;
  gepubliceerdOp?: T;
  gepubliceerdDoor?: T;
  stappen?:
    | T
    | {
        titel?: T;
        uitleg?: T;
        media?:
          | T
          | {
              bestand?: T;
              onderschrift?: T;
              id?: T;
            };
        waarschuwing?: T;
        tip?: T;
        knopOfSchermnaam?: T;
        zoekwoorden?: T;
        variantContext?: T;
        interneNotitie?: T;
        verborgen?: T;
        embeddingStatus?: T;
        embeddingTextHash?: T;
        embedding?: T;
        id?: T;
      };
  embeddingStatus?: T;
  embeddedAt?: T;
  embeddingModel?: T;
  embeddingTextHash?: T;
  embedding?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kennisbasis-onderwerpen_select".
 */
export interface KennisbasisOnderwerpenSelect<T extends boolean = true> {
  onderwerp?: T;
  doel?: T;
  officieleTerm?: T;
  synoniemen?: T;
  voorbeeldvragen?: T;
  toelichting?: T;
  gekoppeldeHandleidingen?: T;
  verduidelijkingsvraag?: T;
  prioriteit?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assistant-conversations_select".
 */
export interface AssistantConversationsSelect<T extends boolean = true> {
  source?: T;
  question?: T;
  hasAnswer?: T;
  answer?: T;
  reasoning?: T;
  confidence?: T;
  sources?:
    | T
    | {
        label?: T;
        refCollection?: T;
        refId?: T;
        title?: T;
        chapterTitle?: T;
        similarity?: T;
        url?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        handleidingId?: T;
        stepId?: T;
        stepNummer?: T;
        id?: T;
      };
  model?: T;
  inputTokens?: T;
  outputTokens?: T;
  totalTokens?: T;
  answerTimeMs?: T;
  feedbackRating?: T;
  feedbackMissing?: T;
  user?: T;
  previousQuestion?: T;
  intentieType?: T;
  kennisbasisOnderwerp?: T;
  kennisbasisKandidaten?: T;
  gebruikteOfficieleTerm?: T;
  gebruikteSynoniem?: T;
  contactFormSubmitted?: T;
  geenHandleidingGevonden?: T;
  verbeterStatus?: T;
  promptVersion?: T;
  retrievalVersion?: T;
  kennisbasisVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assistant-eval-questions_select".
 */
export interface AssistantEvalQuestionsSelect<T extends boolean = true> {
  question?: T;
  category?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assistant-eval-runs_select".
 */
export interface AssistantEvalRunsSelect<T extends boolean = true> {
  evalQuestion?: T;
  question?: T;
  rewrittenQuery?: T;
  retrievalFase?: T;
  hits?:
    | T
    | {
        type?: T;
        refId?: T;
        title?: T;
        chapterTitle?: T;
        similarity?: T;
        priority?: T;
        bronrol?: T;
        id?: T;
      };
  contextText?: T;
  hasAnswer?: T;
  answer?: T;
  reasoning?: T;
  confidence?: T;
  sources?:
    | T
    | {
        label?: T;
        refCollection?: T;
        refId?: T;
        title?: T;
        chapterTitle?: T;
        similarity?: T;
        url?: T;
        id?: T;
      };
  model?: T;
  verdict?: T;
  opmerkingen?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Gmail-helpdeskkoppeling (alleen-lezen toegang). Koppelen/herkoppelen: log in op /admin en open /api/gmail/oauth/start in dezelfde browser.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gmail-connection".
 */
export interface GmailConnection {
  id: number;
  /**
   * Succesvol gekoppeld helpdesk-adres.
   */
  emailAddress?: string | null;
  /**
   * AES-256-GCM-ciphertext — nooit de platte token.
   */
  encryptedAccessToken?: string | null;
  /**
   * AES-256-GCM-ciphertext — nooit de platte token.
   */
  encryptedRefreshToken?: string | null;
  tokenExpiresAt?: string | null;
  scopes?: string[] | null;
  connectedAt?: string | null;
  /**
   * Wordt gezet door elke synchronisatieronde, ongeacht het resultaat per thread.
   */
  lastSyncAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Test semantisch zoeken over kennisbronnen, conceptkennisartikelen en artikelen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-search".
 */
export interface KnowledgeSearch {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Test de AI-assistent tegen de vaste vragenset (40 vragen) of een losse vraag, met volledige retrieval-diagnostiek en handmatige beoordeling.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assistant-eval".
 */
export interface AssistantEval {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * De klikbare voorbeeldvragen onder het invoerveld op de helpdesk-homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "helpdesk-voorbeeldvragen".
 */
export interface HelpdeskVoorbeeldvragen {
  id: number;
  /**
   * Worden direct verstuurd zodra een bezoeker erop klikt.
   */
  vragen?:
    | {
        tekst: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gmail-connection_select".
 */
export interface GmailConnectionSelect<T extends boolean = true> {
  emailAddress?: T;
  encryptedAccessToken?: T;
  encryptedRefreshToken?: T;
  tokenExpiresAt?: T;
  scopes?: T;
  connectedAt?: T;
  lastSyncAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-search_select".
 */
export interface KnowledgeSearchSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assistant-eval_select".
 */
export interface AssistantEvalSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "helpdesk-voorbeeldvragen_select".
 */
export interface HelpdeskVoorbeeldvragenSelect<T extends boolean = true> {
  vragen?:
    | T
    | {
        tekst?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'articles';
      value: number | Article;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}